### ISSUE TITLE
Can´t get it to work

### ISSUE THREAD

**Issue by Anden78** [Xkhi/MMM-Vasttrafik-PublicTransport#7]
Hi

Just reupdated my MagicMirror and everything is working, but I can´t get MMM-Vasttrafik-PublicTransport to work. I have used the old one (Application v2) But thisone v4 I have trouble with
I have a developeraccount and have created the Application and have the access tokens , but the M wont start

Is there anything you can help me with?

MM is all up to date and runs on RPi 3b (If I disable this module in config, MM startes fine)

0|MagicMirror | [29.02.2024 19:35.25.415] [ERROR] (node:142623) UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/request-promise/lib/tp.js'. Please verify that the package.json has a valid "main" entry
0|MagicMirror | at tryPackage (node:internal/modules/cjs/loader:445:19)
0|MagicMirror | at Function._findPath (node:internal/modules/cjs/loader:687:18)
0|MagicMirror | at node:internal/modules/cjs/loader:1070:27
0|MagicMirror | at Function. (node:electron/js2c/browser_init:2:116118)
0|MagicMirror | at Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
0|MagicMirror | at node:internal/modules/cjs/loader:929:27
0|MagicMirror | at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMirror | at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMirror | at require (node:internal/modules/cjs/helpers:121:18)
0|MagicMirror | at Object. (/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_helper.js:16:17)
0|MagicMirror | at Module._compile (node:internal/modules/cjs/loader:1271:14)
0|MagicMirror | at Object..js (node:internal/modules/cjs/loader:1326:10)
0|MagicMirror | at Module.load (node:internal/modules/cjs/loader:1126:32)
0|MagicMirror | at node:internal/modules/cjs/loader:967:12
0|MagicMirror | at Function._load (node:electron/js2c/node_init:2:13357)
0|MagicMirror | at Module.require (node:internal/modules/cjs/loader:1150:19)
0|MagicMirror | (Use electron --trace-warnings ... to show where the warning was created)
0|MagicMirror | [29.02.2024 19:35.25.416] [ERROR] (node:142623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
0|MagicMirror | Warning: vkCreateInstance: Found no drivers!
0|MagicMirror | Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
0|MagicMirror | at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
0|MagicMirror | at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
0|MagicMirror | at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
0|MagicMirror | at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
0|MagicMirror | at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)

**Comment by Anden78** [comment]
[ERROR] (node:2233) UnhandledPromiseRejectionWarning: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport/node_modules/request-promise/lib/tp.js'. Please verify that the package.json has a valid "main" entry

**Comment by herrenP** [comment]
I'm a bit late to the party, but if you still have issues then I assume all you need to do is:

1. `cd /home/pi/MagicMirror/modules`
2. `rm -rf MMM-Vasttrafik-PublicTransport`
3. `git clone https://github.com/Xkhi/MMM-Vasttrafik-PublicTransport`
4. `npm install`
5. Restart MagicMirror

If you are sure your current `/home/pi/MagicMirror/modules/MMM-Vasttrafik-PublicTransport` is fine already, then skip step 1-3.
